version: "3"

services:
  database:
    image: mariadb:latest
    container_name: database
    restart: always
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - ./services/database:/docker-entrypoint-initdb.d
      - database_data:/var/lib/mysql
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    build: ./services/api
    container_name: api
    restart: always
    ports:
      - ${API_PORT:-8082}:80
    depends_on:
      - database
      - socket
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dashboard:
    build:
      context: ./services/dashboard
      args:
        - REACT_APP_API_URL=${API_BASE_URL}
        - REACT_APP_RPI_URL=${RPI_URL}
        - REACT_APP_SOCKET_URL=${SOCKET_URL}
    container_name: dashboard
    restart: always
    ports:
      - ${DASHBOARD_PORT:-8083}:3000
    depends_on:
      - database
      - socket
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  socket:
    build: ./services/socket
    container_name: socket
    restart: always
    ports:
      - ${SOCKET_PORT:-8084}:3000
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # optional
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  database_data:
